fix: #identify argument type
segmentio/analytics-react-native pull request #384
Opened 2021-11-23 12:08 UTC by raminos

Hello library maintainers 👋 ,

thanks for this lovely library! @alan-eu we are happily using your service but we came across an incoherence between your docs and your code which I attempt to fix in this PR.

I read your contributing guidelines but couldn't find a pull request template. I hope the format I chose is okay.

## Problem

In your [docs](https://segment.com/docs/connections/sources/catalog/libraries/mobile/react-native/#identify) you state for the `userId` argument of the `identify` method:

> The database ID for this user. If you don’t know who the user is yet, you can omit the `userId` and just record `traits`.

But with the current implementation Typescript won't allow us to omit a `userId`. We circumvent this issue by passing `undefined as any` but this is suboptimal.

## Solution

I tried to adjust the `identify` method's behaviour in a way that is in line with the existing logic, namely:

- `userId` can be `undefined`
- if `userId` is false (so `undefined` or `""`) the store is not updated

## Tests

I added a test case checking that only the user traits are updated when passing `undefined` as a `userId`. I tried to follow the preexisting unit test style.

As stated in the guidelines I ran all the scripts mentioned to check that tests, linting and the typescript compiler pass.

I'm looking forward to your comments!

Best,
Ramin

2021-11-23 19:51 UTC, oscb requested changes
Thanks so much for noticing this and taking action! 
I left some minor suggestions but otherwise this looks good!

2021-11-23 19:51 UTC, oscb commented on packages/core/src/analytics.ts
> +  identify(userId: string | undefined, userTraits?: UserTraits) {
For consistency, lets use the optional as:
```suggestion
  identify(userId?: string, userTraits?: UserTraits) {
```

2021-11-23 19:51 UTC, oscb commented on packages/core/src/analytics.ts
> +    if (userId) {
Let's put a strict undefined check here:
```suggestion
    if (userId !== undefined) {
```

2021-11-23 23:04 UTC, raminos commented
Thanks @oscb for your fast and positive feedback! I applied your suggestions 😊

2022-01-05 17:15 UTC, alanjcharles commented
Hi @raminos Happy New Year! looks like there is still one comment left in our review. Happy to merge once that's been accounted for.

2022-01-21 00:07 UTC, raminos commented
> Hi @raminos Happy New Year! looks like there is still one comment left in our review. Happy to merge once that's been accounted for.

Hi @alanjcharles I totally missed that I didn't update the second comment! Thanks for reminding me 😍  commit is comming in a sec!

2022-01-21 00:25 UTC, raminos commented
@alanjcharles the code changed a bit in the meantime. The ternary operator is not super pretty but it gets the work done. Is there something I should change?

2022-01-24 19:24 UTC, alanjcharles commented
@raminos sorry for the delay!! we've had to take some unexpected time out of office in the past few weeks. Thanks so much for the update. I can take a closer look in a bit and let you know. Thanks again

2022-01-26 18:27 UTC, oscb approved these changes

2022-02-03 20:09 UTC, alanjcharles commented
@raminos we're ready to merge this as soon as the test you added passes! It looks pretty straightforward but let me know if I can help at all. Thanks!

2022-02-09 20:05 UTC, alanjcharles commented
accounted for in #436 thanks again!

2022-02-09 20:05 UTC, closed without merging