fix: add fix for deviceId on android builds
segmentio/analytics-react-native pull request #405
Opened 2022-01-11 17:37 UTC by alanjcharles

fix for #397

2022-01-11 18:16 UTC, oscb requested changes

2022-01-11 18:16 UTC, oscb commented on packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt
> +    fun getContextInfo(collectDeviceId: Boolean, promise: Promise) {
We should keep the params as before so as to not differ from iOS. Also the config makes it more extendable.

2022-01-11 18:16 UTC, oscb commented on packages/core/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt
> +      contextInfo.putString("deviceId", getUniqueId(collectDeviceId))
We should check the config as before to only request it when the config says so.

2022-01-12 08:45 UTC, Kerumen approved these changes

2022-01-12 08:45 UTC, Kerumen approved these changes

2022-01-12 15:40 UTC, oscb approved these changes

2022-01-24 17:12 UTC, merged