feat: update react native in example to 0.69.2
segmentio/analytics-react-native pull request #613
Opened 2022-07-21 22:08 UTC by alanjcharles

Updates react native version in example app to `0.69.2` to support new react native architecture

2022-07-25 15:59 UTC, oscb commented
Looks good. Only request can you also update the readme here for the instructions on how to import correctly and setup the trackdeeplinks after this change?

2022-07-25 16:01 UTC, alanjcharles commented
@oscb thanks! Definitely can do.

2022-07-26 17:35 UTC, oscb commented on example/package.json
> +    "@segment/sovran-react-native": "0.4.2",
Upgrade also the package.json in core to use this specific version of sovran

2022-07-26 17:35 UTC, oscb requested changes
Just one change needed in core

2022-07-26 17:43 UTC, oscb approved these changes

2022-07-26 23:51 UTC, oscb approved these changes

2022-07-27 00:20 UTC, merged

2022-07-27 00:22 UTC, oscb commented
:tada: This PR is included in version @segment/analytics-react-native-v2.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@segment/analytics-react-native/v/2.5.0)
- [GitHub release](https://github.com/segmentio/analytics-react-native/releases/tag/%40segment/analytics-react-native-v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: