fix: bump kotlin version
segmentio/analytics-react-native pull request #652
Opened 2022-08-23 21:12 UTC by alanjcharles

2022-08-23 23:05 UTC, oscb requested changes
Looks good, but let's wait first for the sovran PR to be released and include the version bump in this PR to launch it all together.

Please also add some comments in the commit of why this is required.

2022-08-24 16:51 UTC, oscb approved these changes

2022-08-24 16:52 UTC, merged

2022-08-24 17:15 UTC, MorenoMdz commented
When can we expect this update to be released?

2022-08-24 18:00 UTC, oscb commented
:tada: This PR is included in version @segment/analytics-react-native-v2.7.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@segment/analytics-react-native/v/2.7.1)
- [GitHub release](https://github.com/segmentio/analytics-react-native/releases/tag/%40segment/analytics-react-native-v2.7.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: