feat: adds branch plugin
segmentio/analytics-react-native pull request #691
Opened 2022-10-07 10:42 UTC by konoufo

2022-10-10 23:04 UTC, oscb requested changes
Just left a few questions, in particular about the `//ts-ignores` that are throughout the files which we should remove

2022-10-13 17:28 UTC, konoufo commented on packages/plugins/plugin-branch/src/methods/__tests__/alias.test.ts
> +//@ts-ignore
nah you're right; red lines in vscode were just hurting my eyes

2022-10-13 17:28 UTC, konoufo commented on packages/plugins/plugin-branch/src/parameterMapping.ts
> +    if (value in mapEventNames) {
the event names ? or the keys ?

2022-10-17 17:07 UTC, konoufo commented on packages/plugins/plugin-branch/src/parameterMapping.ts
> +    if (value in mapEventNames) {
Do you mean like `if (value.capitalize() in mapEventNames)` ?

2022-10-17 17:36 UTC, konoufo commented on packages/plugins/plugin-branch/src/BranchPlugin.ts
> +  // @ts-ignore
Indeed these were useless. Just vscode being clueless and complaining.

2022-10-18 18:05 UTC, oscb approved these changes

2022-10-18 18:05 UTC, merged

2022-11-01 18:15 UTC, oscb commented
:tada: This PR is included in version @segment/analytics-react-native-plugin-branch-v1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@segment/analytics-react-native-plugin-branch/v/1.0.0)
- [GitHub release](https://github.com/segmentio/analytics-react-native/releases/tag/%40segment/analytics-react-native-plugin-branch-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: